### PR TITLE
assumed fill

### PR DESCRIPTION
**Pull request by beauxq**
Using the solver and everything that went into it, I finally have what's needed for an assumed fill.
(This assumed fill uses the solver to get the accessible locations.)

It's weird that `-af` has an `f` for "fill" and the other fills don't have the `f`,
but `-a` is for area - I couldn't think oif anything better.

<details>
  <summary>a sample casual seed</summary>

  ```
   - spaceport -
  sphere:
      get Missile from Torpedo Bay
  sphere:
      get Gravity Boots from Gantry
      get HiJump from Weapon Locker
   - fall from spaceport -
  sphere:
      get Grapple Beam from Ocean Shore: bottom
      get Morph Ball from Ocean Shore: top
  sphere:
      get Bombs from Grand Vault
  sphere:
      get Energy Tank from Impact Crater Alcove
      get Energy Tank from Auxiliary Pump Room
      get Wave Beam from Crypt
      get Gravity Suit from Monitoring Station
      get Energy Tank from Warrior Shrine: AmmoTank bottom
  sphere:
      get Dark Visor from Submarine Nest
      get Plasma Beam from Causeway Overlook
      get Spazer from Antelier
      get Energy Tank from Loading Dock Storage Area
  sphere:
      get Energy Tank from Submarine Alcove
      get Power Bomb from Eribium Apparatus Room
      get X-Ray Scope from Weapon Research
  sphere:
      get Charge Beam from Mezzanine Concourse
      get Speed Booster from Briar: SJBoost
      get Varia Suit from Garden Canal
      get Energy Tank from Norak Escarpment
      get Energy Tank from Antechamber
  sphere:
      get Super Missile from Hive Main Chamber
      get Energy Tank from Infested Passage
      get Energy Tank from Icy Flow
  sphere:
      get Metroid Suit from Ocean Vent Supply Depot
      get Energy Tank from Ancient Basin
      get Energy Tank from Dark Crevice Cache
      get Speed Ball from Crocomire's Lair
  sphere:
      get Space Jump from Archives: SpringBall
      get Energy Tank from Central Corridor: right
      get Ice Beam from Foundry
      get Energy Tank from Restricted Area
      get Energy Tank from Ready Room
  sphere:
      get Screw Attack from Placid Pool
      get Energy Tank from Electromechanical Engine
      get Energy Tank from Fire's Bane Shrine
      get Hypercharge from Tower Rock Lookout
  ```
</details>

<details>
  <summary>a sample expert seed</summary>
  
  ```
   - spaceport -
  sphere:
      get Gravity Boots from Torpedo Bay
   - fall from spaceport -
  sphere:
      get Super Missile from Ocean Shore: bottom
      get Speed Ball from Ocean Shore: top
  sphere:
      get HiJump from Vulnar Caves Entrance
  sphere:
      get Morph Ball from Submarine Nest
  sphere:
      get Grapple Beam from Ocean Vent Supply Depot
      get Energy Tank from Monitoring Station
      get Energy Tank from Sensor Maintenance: ETank
      get Bombs from Trophobiotic Chamber
  sphere:
      get Screw Attack from Benthic Cache
      get Energy Tank from Impact Crater Overlook
      get Energy Tank from Sandy Burrow: ETank
      get Energy Tank from Path Of Swords
  sphere:
      get Wave Beam from Arena
      get Hypercharge from Crypt
      get X-Ray Scope from Warrior Shrine: AmmoTank top
      get Energy Tank from Electromechanical Engine
      get Power Bomb from Generator Manifold
      get Energy Tank from Containment Area
      get Energy Tank from Equipment Locker
      get Metroid Suit from Foundry
      get Missile from Loading Dock Storage Area
  sphere:
      get Energy Tank from Epiphreatic Crag
      get Energy Tank from Grand Chasm
      get Energy Tank from Mezzanine Concourse
      get Energy Tank from Briar: SJBoost
      get Plasma Beam from Antechamber
      get Charge Beam from Glacier's Reach
      get Spazer from Grand Promenade
      get Energy Tank from Sitting Room
      get Energy Tank from Summit Landing
      get Speed Booster from Aft Battery
      get Space Jump from Extract Storage
      get Varia Suit from Forward Battery
      get Ice Beam from Ready Room
  sphere:
      get Gravity Suit from Waste Processing
      get Energy Tank from Magma Lake Cache
      get Dark Visor from Garden Canal
  sphere:
      get Energy Tank from Enervation Chamber
  ```
</details>

### CODE REVIEW

**Comment by beauxq** [comment]
I'm not really happy with the interface.
Because everything was designed around the forward fill, it was hard to fit this in cleanly.

**Comment by beauxq** [comment]
Joonie as the `A` in the file name and thought it was area rando. That's why I don't like the `-af`...

**Comment by randorandy** [comment]
I used D for assumeD fill, though that's not great either

**Comment by randorandy** [comment]
I was close to finishing assumed fill myself, and I was running into trouble on seed generation, running out of locations to place things (which shouldn't happen...) So I will have to look at yours to see what the differences are.

**Comment by randorandy** [comment]
I tried testing this, rolled some, and it has canFly not needing jumpAble which kept putting impact crater items in logic. I tried to fix it myself but started getting worse errors. I know the expert logic is not done yet, but I want to see what this looks like with casual.

**Pull request merged**
