### PR TITLE
logic rework

### PR DESCRIPTION
**Pull request by beauxq**
combine logic so 2 different references don't get out of sync

separate logic data from code that updates logic

work towards being able to start in areas other than the normal drop location

lots of comments on issues I saw with the logic

new data structure for loadout - faster to check if something is in loadout

rename area door so we don't call it a connection if it's not connected

some unit tests to test some aspects of the logic

I've heard from someone on the varia randomizer team that they regret putting numbers of e-tanks in the logic, because people would like to be able to change the amount of energy each e-tank gives. So the logic now references amount of energy instead of number of e-tanks.
```python
energy_req(650, 350) in loadout
```
This means a casual player requires 650 energy, and an expert player can do it with 350.

There is also a logic shortcut for hell runs without varia.
```python
varia_or_hell_run(450) in loadout
```
This will always require varia for casual, but expert can do it with varia or with 450 energy.

### CODE REVIEW

**Comment by randorandy** [comment]
I guess I got started by learning how to edit Total's rando where the different logics were different files. I like that structure, and it was a good way to learn how to edit one of those files to my liking. This merged version, especially in the area-and-requirement-heavy areas like geothermal, starts becoming unwieldy to me. If someone wanted to add their own logic setting here, they would need to do it without messing up the other logics, and that would be pretty hard.

The energy as energy values instead of number of tanks change seems fine, since you said it could pave the way for reduced tank sizes in the future.

I need to look more closely at what you are proposing about the vulnar caves and sunken nest logic.

**Comment by beauxq** [comment]
It's a good point. In this system, adding another logic level could be really messy.

I think the varia randomizer has a better way of handling it. 
The varia randomizer doesn't have separate "casual" and "expert" files for specific item locations or paths through areas.

https://github.com/theonlydude/RandomMetroidSolver/tree/master/standard_presets

The different files for "expert" and "casual" aren't connected to specific locations.
The data there is "what tricks do I know how to do".
But the data for connecting tricks to specific locations in the game is the same for casual and expert and every other logic level.

But the work done so far here doesn't translate as well to that.


Total's is not so bad, I just worry about all the duplicated information.
Would you like separate casual and expert files with these data structures? I can make that happen.

**Comment by strotlog** [comment]
I think a few straightforward logics with documentation is more approachable for players than specifying everything they know/don't know in this case. We don't aim to have the level of customization offered by VARIA, afaik.

Using separate logic files provides the cleanest 'self-documentation' if someone not versed in Python wants to check the logic at a location x difficulty combo.

The way the PR has it does provide sort of the next best thing, but also makes it easy and sensible-looking for someone to start writing logic that consolidates so that logic does NOT separate strictly by level:
```py
    "Generator Manifold": lambda loadout: (
        (
            (jumpAble in loadout) and
            (Super in loadout) and
            (canBomb in loadout) and
            ((
                (ReservoirMaintenanceTunnelR in loadout) and
                (GravitySuit in loadout)
            ) or (
                (GeneratorAccessTunnelL in loadout) and
                (canUsePB in loadout) and
                (MetroidSuit in loadout) and
                (Screw in loadout)
            ) or (
                (ThermalReservoir1R in loadout) and
                (Varia in loadout) and
                (MetroidSuit in loadout) and
                (Screw in loadout)
            ))
        ) or (
            (Expert in loadout) and (
                (jumpAble in loadout) and
                (Super in loadout) and
                (canBomb in loadout) and
                ((
                    (ReservoirMaintenanceTunnelR in loadout) and
                    ((GravitySuit in loadout) or (HiJump in loadout) or (Ice in loadout))
                ) or (
                    (GeneratorAccessTunnelL in loadout) and
                    (canUsePB in loadout) and
                    (MetroidSuit in loadout) and
                    (Screw in loadout)
                ) or (
                    (ThermalReservoir1R in loadout) and
                    (varia_or_hell_run(250) in loadout) and
                    (MetroidSuit in loadout) and
                    (Screw in loadout)
                ))
            )
        )
    ),
```

Related to the possible dev desire to consolidate that, ideally we'd make it straightforward to somehow see how expert and (other logic unnamed in snippet) differ. I'm not sure what the best solution is. Possibly something with logic data files, on which new tools can operate?

**Comment by beauxq** [comment]
separated logic back into 2 files

**Comment by randorandy** [comment]
As I am familiarizing myself with these files, I can understand the benefits. As for the two-way area door logic, that solution will not always work. I am poised to provide asymmetrical logic for the areas with two-colored doors like in service sector and verdite mines. Is it possible to include both?

**Comment by beauxq** [comment]
I'm not sure whether I'm misunderstanding what you're saying.

I thought that the area logic I had here was directional, with only doors making the difference.

```python
        ("CraterR", "SunkenNestL"): lambda loadout: (
            canFly in loadout
        ),
        ("SunkenNestL", "CraterR"): lambda loadout: (
            loadout.has_all(canFly, canUsePB)
        ),
```

from `CraterR` to `SunkenNestL`, you only need `canFly` (for the return logic), and no PBs because if you come in from there, the PB door is open.
In the other direction,
from `SunkenNestL` to `CraterR`, you need both `canFly` and PBs.

If you want to add more differences in different directions, you can.

**Pull request merged**
